### ISSUE TITLE
sac-4 file sizes

### ISSUE THREAD

**Issue by r-lyeh-archived** [mbitsnbites/libsac#1]
sac-8 seems to be generating 8-bits per sample.
however, sac-4 seems to be suboptimal and generating more than 4-bits per sample. 
may i be wrong?

thanks in advance : )

**Comment by mbitsnbites** [comment]
The "4-bit" and "8-bit" sizes refer to the size of each sample in the data stream. However, there is some overhead with the control data for each block that makes the entire file slightly larger than the simple assumed size 4 \* total_number_of_samples / 8, for instance.

For DD8A, each block is 17 bytes long, and contains 16 samples (effective size = 8 \* 17 / 16 = 8.5 bits / sample).

For DD4A, each block is 18 bytes long, and contains 32 samples (effective size = 8 \* 18 / 32 = 4.5 bits / sample).

See [decode_dd4a.cpp](https://github.com/mbitsnbites/libsac/blob/master/src/lib/decoder/decode_dd4a.cpp) for more detailed information, for instance.

I hope this answers your question.

**Comment by r-lyeh-archived** [comment]
aha. it makes sense then :)
thx
